# Travis CI
dist: jammy
language: python

python:
  - "3.11"

env:
  jobs:
    - DASH_VERSION="dash==3.4.0"
    - DASH_VERSION="dash==4.4.1"

cache:
  - pip

install:
  - pip install -r requirements.txt "$DASH_VERSION"
  - pip install -r dev_requirements.txt
  - python setup.py develop

services:
  - redis-server

script:
  - pushd demo
  - pytest demo --cov=demo --cov=django_plotly_dash --cov-report term-missing

after_success:
  - coveralls
